<?php

/**
 * @file
 * Contains example code demonstrating topics covered in Chapter 2.
 */


module_load_include('inc', 'pde', 'includes/tools');


// @ignore sniffer_commenting_inlinecomment_spacingafter:file


/**
 * Implements hook_entity_info().
 */
function pde_02_entity_info() {
  pde_trace_funct();

  $entity = array();
  $entity['ingredient'] = array(
    'label' => t('Ingredient'),
    // Entity API parameter. See hook_entity_info in entity/tests/
    // entity_test.module and entity/README.txt.
    'entity class' => 'Entity',
    // EntityAPIController is a class of Entity API.
    'controller class' => 'EntityAPIController',
    'base table' => 'ingredient',
    'entity keys' => array(
      'id' => 'iid',
      'label' => 'name',
    ),
    'fieldable' => FALSE,
  );

  return $entity;
}


/**
 * Implements hook_entity_property_info_alter().
 *
 * Called after flush of cache.
 */
function pde_02_entity_property_info_alter(&$info) {
  pde_trace_funct();
  // dpm($info);

  $properties = &$info['ingredient']['properties'];

  $properties['name'] += array(
    'setter callback' => 'entity_property_verbatim_set',
  );
}
